language: cpp
compiler:
    - gcc
    - clang
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-5
install:
  - ./install-gtest.sh
before_scripts:
  - if [ "$CXX" = "g++" ]; then export CXX=/usr/bin/g++-5; fi
  - if [ "$CXX" = "clang++" ]; then export CXX=/usr/bin/clang++-3.6; fi
script: make test
